import Head from "next/head";
import Post from "../components/Post";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import Bio from "../components/Bio";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Bio
          headshot="https://lh3.googleusercontent.com/a-/AOh14GjHOZkxn2NhM_JH8nvW5FmzW1ZmGAQt7Y5mADG-=s288-p-no"
          name="JC Picol"
          tagline="Creating beautiful user expierence for new decentralized tech "
          role="Frontend Developer"
        />

        <ul className={styles.posts}>
          <li>
            <Post
              content="I'm working on using figma and using Next js with Storybook."
              date="10/25/21"
            />
          </li>
          <li>
            <Post
              content="I'm working on using figma and using Next js with Storybook."
              date="10/25/21"
            />
          </li>
          <li>
            <Post
              content="I'm working on using figma and using Next js with Storybook."
              date="10/25/21"
            />
          </li>
        </ul>

        <form>
          <textarea className={styles.formContent}></textarea>
          <button className={styles.formButton}>Add New Post</button>
        </form>
      </main>
    </div>
  );
}
